### ISSUE TITLE
3.8.2 cannot find its cowfiles on Arch Linux

### ISSUE THREAD

**Issue by lollo03** [cowsay-org/cowsay#49] opened 2024-08-19 14:35 UTC
If you install the latest version using pacman cowsay will come without cowfiles.

If I run: `cowsay -l` I get an empty list.

The directory `/usr/local/share/cowsay `does not exist.

A downgrade to cowsay version 3.04-5 solves the problem

**Comment by apjanke** [comment] 2024-08-19 16:10
That's not good! Might be a /usr/local vs. /usr difference, maybe as seen in https://github.com/cowsay-org/cowsay/issues/40.

I'll get right on this.

**Comment by apjanke** [comment] 2024-08-19 18:24
So, looking at this a bit more: I believe the installation using a pacman package should install to `/usr`, not `/usr/local`, and the cows will be under `/usr/share/cowsay`, not `/usr/local/share/cowsay`. The `cowsay` binary should be able to detect this and pick them up properly.

Any chance you have an environment variable or similar that's configured to unconditionally point to `/usr/local/share/cowsay`? Like, `$COWPATH` plus `$COWSAY_ONLY_COWPATH` in your `~/.bashrc`?

Could you run a pacman command to list all the files installed by that cowsay package, and paste the output here? (I don't know the exact command to do that.)

I tried reproducing this on an Ubuntu box by doing an install to `/usr`, and the `make DESTDIR="${pkgdir}" install prefix=/usr` that I think the pacman PKGBUILD formula is doing, and I couldn't reproduce it. `cowsay -l` reported cows, and `cowsay "moo"` etc. worked. That was just a quick test; I'll try to do a better repro, and build an Arch test box specifically.

Might be that recent fixes to the Makefile fixed something here, and I'm not repro-ing with the right code.

(Anyone know the quickest easiest way to get an Arch build & test VM going? Preferably under VMware Fusion, Parallels, or UTM on a Mac, or in some low/no-cost VM or USB drive on a Windows PC.)

**Comment by lollo03** [comment] 2024-08-20 07:31
It could be my problem, but this is strange... why 3.04-5 works but 3.8.2-1 does not?

Also, I checked $COWPATH and $COWSAY_ONLY_COWPATH, they are both empty. Upon further inspection, it seems like 3.8.2-1 creates the "cowsay" directory in `/usr/share/`. This directory contains "cows" and "site-cows"

Meanwhile, the 3.04-5 version creates a "cow" directory in `/usr/share/`. This directory contains the cowfiles.

I don't really know what is happening here...
If it could help in any way I'm using [this](https://github.com/bhayward93/Linus-rants-ZSH) plugin in my zsh shell.

**Comment by lollo03** [comment] 2024-08-20 14:29
For the 3.04 package:
```
❯ which cowsay
/sbin/cowsay
❯ cowsay --version
/sbin/cowsay version [unknown] calling Getopt::Std::getopts (version 1.13 [paranoid]),
running under Perl version 5.38.2.
  [Now continuing due to backward compatibility and excessive paranoia.
   See 'perldoc Getopt::Std' about $Getopt::Std::STANDARD_HELP_VERSION.]
```

For the 3.8.2 package:
```
❯ which cowsay
/sbin/cowsay
❯ cowsay --version
/sbin/cowsay version 3.8.2 calling Getopt::Std::getopts (version 1.13),
running under Perl version 5.38.2.

```

The output for ` env | grep COW` is empty.

If I install the 3.8.2 package and run `/usr/bin/cowsay ` it works, however, if I run `cowsay` it doesn't work.

**Comment by apjanke** [comment] 2024-08-20 14:39
How did your cowsay end up in `/sbin` instead of `/usr/bin` or `/bin`? Could you do a `ls -l /sbin/cowsay` and paste the output? Is putting copies or symlinks of regular programs in to `/sbin` a normal Arch thing to do?

I've got a lead: Looks like the installation location detection logic, and thus prefix selection, doesn't work right in some cases, depending on the path used to invoke it. It depends on being able to see that its parent dir is named "bin", based on the path to `cowsay` used in the _command line_, not the "actual" location of the `cowsay` file on disk.

```
[cowsay] $ which cowsay
/usr/local/bin/cowsay
[cowsay] $ cowsay hello
__FILE__ = /usr/local/bin/cowsay
parent_dir = /usr/local/bin
 _______
< hello >
 -------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
[cowsay] $
[cowsay] $ cd /usr/local/bin
[bin] $ ./cowsay hello
__FILE__ = ./cowsay
parent_dir = .
cowsay: Could not find cowfile for 'default.cow'!
[bin] $
```

See: https://github.com/cowsay-org/cowsay/issues/55

And it looks like your "cowsay is `/sbin/cowsay`" situation here will hit that, because the parent directory is not "bin". So it thinks it is running from a local repo instead of an installation location, and uses something like `../share/cows` as its cowpath, instead of `$prefix/share/cowsay/cows`.

I think that's a bug in cowsay, and we can fix this. In the meantime, maybe removing that `/sbin/cowsay`will fix you up, if that's not a standard part of the installation of the Arch package?

**Comment by lollo03** [comment] 2024-08-20 14:47
I have no idea why cowsay got installed in /sbin. The output for `ls -l /sbin/cowsay` is:
```
-rwxr-xr-x 1 root root 9142 Aug 17 14:02 /sbin/cowsay
```

Also, take a look at this:
![image](https://github.com/user-attachments/assets/b697c136-9e9c-4fcd-9202-c9ff525c3031)

**Comment by moralground** [comment] 2024-08-20 14:48
The cowsay binary in arch is /usr/bin/cowsay. The directories /bin and /sbin are symlinks to /usr/bin, as is now the linux standard (for better or worse). There is nothing in /usr/local/bin by default and no arch packages should be putting things there.  Not sure if any of that is helpful, but I still confirm that a default cowsay install on arch works just fine here.

OP may have a custom $PATH that puts /sbin before /usr/bin. If I call "/sbin/cowsay test" explicitly, it does error out with "Could not find cowfile for 'default.cow'!"

**Comment by lollo03** [comment] 2024-08-20 14:53
> The cowsay binary in arch is /usr/bin/cowsay. The directories /bin and /sbin are symlinks to /usr/bin, as is now the linux standard (for better or worse). There is nothing in /usr/local/bin by default and no arch packages should be putting things there. Not sure if any of that is helpful, but I still confirm that a default cowsay install on arch works just fine here.
> 
> OP may have a custom $PATH that puts /sbin before /usr/bin. If I call "/sbin/cowsay test" explicitly, it does error out with "Could not find cowfile for 'default.cow'!"

You are right, in my $PATH /sbin comes before /usr/bin , So the problem is my $PATH,

However, I think that this could be considered a bug and should be fixed.

**Comment by apjanke** [comment] 2024-08-20 15:28
> The cowsay binary in arch is /usr/bin/cowsay. The directories /bin and /sbin are symlinks to /usr/bin, as is now the linux standard (for better or worse). There is nothing in /usr/local/bin by default and no arch packages should be putting things there. Not sure if any of that is helpful, but I still confirm that a default cowsay install on arch works just fine here.

Ahh. Yeah, that is helpful.

> You are right, in my $PATH /sbin comes before /usr/bin , So the problem is my $PATH,

That's consistent with everything I've seen here. I think we've identified the cause.

> However, I think that this could be considered a bug and should be fixed.

Yeah, I agree that this is a cowsay bug.

I've got a fix (I think) out on branch apj/dev2408 - https://github.com/cowsay-org/cowsay/tree/apj/dev-2408, commit https://github.com/cowsay-org/cowsay/commit/80353ccfb649296e7546a9d231172c579903a379. It uses `abs_path` to resolve symlinks, handle cases like `./cowsay`, and correctly detect the "real" installation location of cowsay, and get the $prefix and paths from there.

```
[cowsay] $ ls -l ~/tmp/foonly/*
lrwxr-xr-x  1 janke  staff  21 Aug 20 11:25 /Users/janke/tmp/foonly/cowsay -> /usr/local/bin/cowsay
[cowsay] $ PATH=~/tmp/foonly:$PATH
[cowsay] $ which cowsay
/Users/janke/tmp/foonly/cowsay
[cowsay] $ cowsay moo
 _____
< moo >
 -----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
[cowsay] $ cowsay -l
Cow files in /usr/local/share/cowsay/cows:
alpaca beavis.zen blowfish bong bud-frogs bunny cheese cower cupcake daemon
default dragon dragon-and-cow elephant elephant-in-snake eyes flaming-sheep
```

I'm planning to push this out in a 3.8.3 release soon, after some more testing, specifically for the `prefix=/usr` case.

**Comment by apjanke** [comment] 2024-08-20 16:04
Works for me under Ubuntu 22.04 and 24.04. But I don't have an Arch Linux box to test it on, and these Ubuntus don't have `/sbin` as a symlink to `/usr/bin`. Do you want to test it out on Arch for me? If you clone the repo and check out `apj/dev2408` and do a `make install prefix=/usr` (after uninstalling any other cowsay packages), that should get you there. Then do a `make uninstall prefix=/usr` to clean it up afterwards.

**Comment by apjanke** [comment] 2024-08-20 16:31
Think we've got a winner here. I got an Arch Linux VM running under Vagrant, updated it, and did a prefix=/usr install of cowsay from that apj/dev2408 work branch. Seems to work, including when run via `/sbin/cowsay` or having `/sbin` on the `$PATH`.

```
[vagrant@arch cowsay]$ sudo make install prefix=/usr
install -c -d /usr/etc/cowsay/cowpath.d
install -c -d /usr/bin
install -c bin/cowsay /usr/bin/cowsay
ln -s cowsay /usr/bin/cowthink
install -c -d /usr/share/man/man1
install -c -m 644 man/cowsay.1 /usr/share/man/man1/cowsay.1
install -c -m 644 man/cowsay.1 /usr/share/man/man1/cowthink.1
install -c -d /usr/share/cowsay/cows
install -c -m 644 share/cowsay/cows/*.cow /usr/share/cowsay/cows
install -c -d /usr/share/cowsay/site-cows
[vagrant@arch cowsay]$ type cowsay
cowsay is /usr/bin/cowsay
[vagrant@arch cowsay]$ cowsay ciao
 ______
< ciao >
 ------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
[vagrant@arch cowsay]$ /sbin/cowsay ciao
 ______
< ciao >
 ------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
[vagrant@arch cowsay]$ /sbin/cowsay -l
Cow files in /usr/share/cowsay/cows:
alpaca beavis.zen blowfish bong bud-frogs bunny cheese cower cupcake daemon
default dragon dragon-and-cow elephant elephant-in-snake eyes flaming-sheep
fox ghostbusters head-in hellokitty kiss kitty koala kosh llama luke-koala
mech-and-cow meow milk moofasa moose mutilated ren sheep skeleton small
stegosaurus stimpy supermilker surgery three-eyes turkey turtle tux udder
vader vader-koala www
[vagrant@arch cowsay]$ PATH=/sbin:$PATH
[vagrant@arch cowsay]$ hash -r
[vagrant@arch cowsay]$ type cowsay
cowsay is /sbin/cowsay
[vagrant@arch cowsay]$ cowsay ciao
 ______
< ciao >
 ------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
[vagrant@arch cowsay]$ cowsay --version
/sbin/cowsay version 3.8.3-SNAPSHOT calling Getopt::Std::getopts (version 1.13),
running under Perl version 5.38.2.
[vagrant@arch cowsay]$
```

Gonna merge this to main, think about it for a couple hours, and then probably roll a new 3.8.3 release.

**Comment by apjanke** [comment] 2024-08-21 13:24
Cowsay [3.8.3](https://github.com/cowsay-org/cowsay/releases/tag/v3.8.3) is out with this fix. (In this repo and the Homebrew formula; hasn't made it to the Arch pacman package yet AFAIK.) Works in my testing.

Closing this as Fixed. Thanks for the bug report!

**Closed by apjanke** 2024-08-21 13:24 UTC
Labels: bug
